name: Label PR and check title

on:
    pull_request_target:
        branches: ['*']

jobs:
    title:
        runs-on: ubuntu-latest
        name: PR Title
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
